feat/google-calendar-integration
blueprinthub/blueprint-firebase pull request #59
Opened 2023-09-20 22:24 UTC by yarn-rp

## Description
Provides the implementation of a whole new module called `events`. This module wil be in charge of handling `events` related stuff like calendar platforms etc. 

In general this is almost the same that we are going in the task module, but for events. A few small naming changes are done in the architecture of it. The classes are the same, but the folder structure made more sense to me this way. If we decide to go this way, we should refactor also on the events module. 

### This PR does not include interface implementation
For now we have a trigger on the authenticators subcollection of the user. This trigger was made specifically for the tasks feature, but now should support calendar integrations too. That will be achieved in a different PR. 

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2023-09-21 14:25 UTC, jvaldesgonzalez requested changes
everything looks good, great job, thank you. Only the nit of the comments that in several cases seem to me to be superfluous... but it's just a nit. I am the other side of the coin haha.

2023-09-21 14:25 UTC, jvaldesgonzalez commented on .vscode/settings.json
suggestion: add the .vscode folder to gitignore
if we are going to commit a specific configuration that we want to reinforce, let's try to make it cross-editor, prettier type, etc...

2023-09-21 14:54 UTC, jvaldesgonzalez requested changes

2023-09-21 14:54 UTC, jvaldesgonzalez commented on functions/src/modules/events/domain/entities/attendant-status.enum.ts
> +export enum AttendantStatus {
suggestion: enums must be CONSTANT_CASED or PascalCased.. I prefer PascalCase

2023-09-21 14:56 UTC, jvaldesgonzalez commented on functions/src/modules/events/domain/entities/attendant-status.enum.ts
> +export enum AttendantStatus {
take [this file](https://github.com/blueprinthub/blueprint-firebase/blob/main/functions/src/modules/tasks/domain/entities/platform.enum.ts) as a reference if you need those lowercased

2023-09-21 23:31 UTC, yarn-rp commented on functions/src/modules/events/domain/entities/attendant-status.enum.ts
> +export enum AttendantStatus {
Thanks! I just went with PascalCase. Shouldn't we use a rule for that? I feel like I could make that mistake one more time, since thats Dart estandart.

2023-09-21 23:47 UTC, yarn-rp commented on .vscode/settings.json
That also reminds me that I need to fix my vsCode config. Seems like I have something wrong on my end, cause the project is giving me weird errors everywhere. This is the first project that happens to me, but I'm pretty sure is on my end so I'll figure it out

2023-09-22 14:42 UTC, jvaldesgonzalez approved these changes

2023-09-22 14:43 UTC, merged